FROM ocr-docker-remote.artifactory.oci.oraclecorp.com/os/oraclelinux:8-slim

RUN set -eux; microdnf -y update;

RUN microdnf install dotnet-sdk-8.0 && \
    microdnf install dotnet-sdk-6.0 && \
    microdnf install dotnet-sdk-3.1 && \
    microdnf clean all

CMD ["dotnet", "--version"]
