FROM container-registry.oracle.com/os/oraclelinux:8-slim

RUN microdnf install aspnetcore-runtime-6.0 && \
      microdnf install aspnetcore-runtime-3.1 && \
      microdnf install dotnet-sdk-6.0 && \
      microdnf clean all

